WIFI_SSID = "Wifi Network"
WIFI_PASS = "password"
TOKEN = "Your ubidots API credentials" #Put here your TOKEN
DEVICE_LABEL = "picowboard" # Assign the device label desire to be send
VARIABLE_LABEL1 = "temperature"  # Assign the variable label desire to be send
VARIABLE_LABEL2 = "humidity"
VARIABLE_LABEL3 = "light"
VARIABLE_LABEL4 = "led"
VARIABLE_LABEL5 = "switch"
